/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package police;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.time.Instant;
import java.time.ZonedDateTime;
import java.util.Timer;
import java.util.TimerTask;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import net.dv8tion.jda.api.EmbedBuilder;
import net.dv8tion.jda.api.JDA;
import net.dv8tion.jda.api.entities.TextChannel;
import net.dv8tion.jda.api.entities.User;
import org.json.JSONArray;
import org.json.JSONObject;
import org.ocpsoft.prettytime.PrettyTime;
import police.configs.ConexaoDB;
import police.configs.Config;
import police.configs.ConfigUsuario;
import police.configs.GetImages;
import police.configs.SNWindows;
import police.configs.Usuario;

/**
 *
 * @author John
 */
public class CorporacaoUsuarios extends javax.swing.JFrame {

    /**
     * Creates new form Corporacao
     */
    JButton[] PMenos = new JButton[50];
    JButton[] PMais = new JButton[50];
    JButton[] PRemover = new JButton[50];
    
    JLabel[] Nome = new JLabel[50];
    JLabel[] Patente = new JLabel[50];
    JLabel[] FzeOq = new JLabel[50];
    
    Usuario usuarios = new Usuario();
    ConexaoDB conexao = new ConexaoDB();
    InicializadorMain policia = new InicializadorMain();
    Config config = new Config();
    
    String passaporteg = "";
    String nomeusuariog = "";
    
    String PassaAddU="";
    String NomeU="";
    String DiscordAddU="";
    JSONArray discordDBarray = new JSONArray();
    
    String NomeP="";
    int PatenteP=0;
    int PatentePA=0;
    int PatenteInsigna=0;
    int PatenteInsignaA=0;
    String CodigoP="";
    String Discord="";
    int PassaporteP=-1;
    
    int PassCida=-1;
    
    int TimerAtte = 30;
    
    boolean newcodigo = false;
    
    JDA jda;
    
    JSONObject usuariosDB = new JSONObject();
    JSONArray usuariosDBarray = new JSONArray();
    JSONArray usuarioMyDBarray = new JSONArray();
    JSONArray hierarquiaDBarray = new JSONArray();
    
    
    private static final String ALPHA_NUMERIC_STRING = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
    
    public CorporacaoUsuarios() {
        initComponents();
        IniciarDados();
        DiscordBot();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void IniciarDados(){
        
        getContentPane().setBackground(new java.awt.Color(13, 32, 64));
        pnl_recrutar.setBackground(new java.awt.Color(13, 32, 64));
        jPanel2.setBackground(new java.awt.Color(13, 32, 64));
        //jPanel3.setBackground(new java.awt.Color(13, 32, 64));
        informacoes.setBackground(new java.awt.Color(13, 32, 64));
        config_usuario.setBackground(new java.awt.Color(13, 32, 64));
        
        this.setLocationRelativeTo(null);
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(config.img_CBIcone)));
        if(InicializadorMain.ModoOffline){
            this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("imagens/CB2.png")));
        }else{
            this.setIconImage(new ImageIcon(GetImages.LogoCB).getImage());
        }
        
        /*int totalpatentes = 14;
        Bpatentes.removeAllItems();
        desfazer.setVisible(false);
        
        for (int i=0; i<=usuarios.Qntptt; i++){
            Bpatentes.addItem(usuarios.Patentes(i));
        }*/
        
        jPanel2.revalidate();
        jPanel2.repaint();
        
        bt_rebaixar.setEnabled(false);
        bt_promover.setEnabled(false);
        
        btexonerado.setEnabled(false);
        
        usuariosDBarray = InicializadorMain.usuariosDBarray;
        discordDBarray = InicializadorMain.discordDBarray;
        
        //usuariosDBarray = usuarios.AttDBUsuarios();
        //discordDBarray = usuarios.AttDBDiscord();
        
        //AttDBUsuarios();
        Erro("");
        AttDBHierarquia();
        TabelaAtt();
        
        Dados();
        Timere();
    }
    public void DiscordBot(){
        jda = policia.getJDA();
        /*try{

            jda = new JDABuilder("NTQxMTIxMzIwNjcxNTEwNTI4.Xfl2zQ.PBtKk452VMOzYWNsG9uvYbOu4OY")         // The token of the account that is logging in.

                    .addEventListeners(new DiscordMessage())  // An instance of a class that will handle events.

                    .build();

            jda.awaitReady(); // Blocking guarantees that JDA will be completely loaded.

            System.out.println("Finished Building JDA!");
            
            

        }catch (InterruptedException e)

        {

            //Due to the fact that awaitReady is a blocking method, one which waits until JDA is fully loaded,

            // the waiting can be interrupted. This is the exception that would fire in that situation.

            //As a note: in this extremely simplified example this will never occur. In fact, this will never occur unless

            // you use awaitReady in a thread that has the possibility of being interrupted (async thread usage and interrupts)

            e.printStackTrace();

        } catch (LoginException ex) {
            Logger.getLogger(Corporacao.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }
    
    public void Timere (){
        int delay = 500;   // tempo de espera antes da 1ª execução da tarefa.
        int interval = 1000;  // intervalo no qual a tarefa será executada.
        Timer timer = new Timer();
        timer.scheduleAtFixedRate(new TimerTask() {
          public void run() {
            //System.out.println("Olá World!"); 
            if(TimerAtte > 0){
                TimerAtte--;
                String taimer;
                if(TimerAtte>9){
                    taimer=""+TimerAtte;
                }else{
                    taimer="0"+TimerAtte;
                }
                attTab.setText("ATUALIZAR ("+taimer+")");
                attTab.setEnabled(false);
            }else{
                attTab.setEnabled(true);
                attTab.setText("ATUALIZAR AGORA");
            }
          }
        }, delay, interval);
    }
    
    public void Dados(){
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        
        membros.getColumnModel().getColumn(0).setPreferredWidth(20);
        membros.getColumnModel().getColumn(1).setPreferredWidth(50);
        membros.getColumnModel().getColumn(2).setPreferredWidth(40);
        //membros.getColumnModel().getColumn(3).setPreferredWidth(40);
        
        
        membros.getColumnModel().getColumn(0).setHeaderRenderer(centerRenderer);
        membros.getColumnModel().getColumn(1).setHeaderRenderer(centerRenderer);
        membros.getColumnModel().getColumn(2).setHeaderRenderer(centerRenderer);
        //membros.getColumnModel().getColumn(3).setHeaderRenderer(centerRenderer);
        
        membros.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        membros.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        membros.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        //membros.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        
        //TabelaAtt();
        
        //editar.setEnabled(false);
        
        Alterou();
    }
    public void TabelaAtt(){
        DefaultTableModel model = (DefaultTableModel) membros.getModel();
        model.setRowCount(0);
        pesquisa.setText("");
        PesquisarT();
        TimerAtte=20;
        //System.out.println("usuariosDBarray: "+usuariosDBarray.toString()+" ?°/ ");
        for(int i = 0; i < InicializadorMain.usuariosDBarray.length(); i++){
            JSONObject o = InicializadorMain.usuariosDBarray.getJSONObject(i);
            int pass = o.getInt("id_usuario");
            int pter=0;
            boolean lspd=false;
            for(int i2 = 0; i2 < hierarquiaDBarray.length(); i2++){
                JSONObject ohier = hierarquiaDBarray.getJSONObject(i2);
                //System.out.println("hierarquiaDBarray: "+ohier.toString()+" // ");
                if(pass==ohier.getInt("id_usuario")){
                    pter = ohier.getInt("cargo");
                    lspd = pter!=99;
                }
            }
            if(lspd){
                //String discord = Usuario.DiscordPorID(pass);
                
                //System.out.println("o.DBarray: "+o.toString()+" ?°/ ");
                /*if(discord.length() >= 10){
                    discord="SIM";
                }else{
                    discord="NÃO";
                }*/
                String nome = o.getString("nome")+" "+o.getString("sobrenome");
                if(pter != 99 && pter != 16){
                    //String patenter = usuarios.Patentes(pter);
                    JSONObject cargo_usuario = SNWindows.getCargoObjUserID(pass);
                    String patente = cargo_usuario.getString("nome_cargo");
                    model.addRow(new Object[]{pass, nome, patente});
                }
            }
            //}
        }
    }
    
    public void Alterou(){
        boolean BOL = false; //true
        if(pttatual.getText().equals(newptt.getText()))BOL=false;
        desfazer_alteracoes.setEnabled(BOL);
        salvar_ptt.setEnabled(BOL);
    }
    
    public void MensagemDiscord(JSONObject DiscordTag){
        //User usuar = jda.getUserByTag(DiscordTag);
            int passaporte=DiscordTag.getInt("passaporte");
            String nome=DiscordTag.getString("nome");
            String codigo=DiscordTag.getString("codigo");
            
            String discord=DiscordTag.getString("discord");//Usuario.DiscordPorID(passaporte);
            if(!"".equals(discord)){
                String n_cidade = InicializadorMain.info_cidade.getString("nome_cidade");
                String n_policia = InicializadorMain.info_cidade.getString("nome_policia");
                String n_policiaabv = InicializadorMain.info_cidade.getString("nome_policia_abv").toUpperCase();
                String url_logo = InicializadorMain.info_cidade.getString("url_logo");
                
                String nome_patente=DiscordTag.getString("nome_patente");
                int OqueFez=DiscordTag.getInt("oqfez");
                String OqFez,OqFez2;
                switch (OqueFez) {
                    case 1:
                        OqFez="Você foi recrutado";
                        OqFez2="Recrutado para a "+n_policiaabv+" como "+nome_patente+".";
                        break;
                    case 2:
                        OqFez="Você foi recrutado";
                        OqFez2="Recrutado para a "+n_policiaabv+" como ";
                        break;
                    default:
                        OqFez="Mudança de Acesso";
                        OqFez2="Foi modificado o seu código de acesso do **Computador de Bordo**.";
                        break;
                }

                User usuar = jda.getUserById(discord);

                EmbedBuilder eb = new EmbedBuilder();
                
                
                eb.setAuthor(n_cidade+" "+n_policiaabv+" - Mudança de Acesso ", "https://imgur.com/vBK8vRk.png");
                eb.setFooter("Computador de Bordo • "+n_cidade, "https://imgur.com/vBK8vRk.png");
                        
                eb.setColor(new Color(0x0D2040));
                eb.setDescription(OqFez2+
                    "\n\n**Nome Completo:** "+nome+
                    "\n**Passaporte:** "+passaporte+
                    "\n**Código:** "+codigo);

                //eb.addField(":regional_indicator_i: :regional_indicator_n: :regional_indicator_f: :regional_indicator_o:   :regional_indicator_c: :regional_indicator_i: :regional_indicator_d: :regional_indicator_a: :regional_indicator_d: :regional_indicator_a: :regional_indicator_o:", "Você pode recursar a "+Apree+" com um advogado pelo número do procotolo.", false);
                /*eb.addField("Nome Completo", ":page_facing_up: "+nome, true);
                eb.addField("Passaporte", ":bookmark_tabs: "+passaporte, true);
                eb.addField("Código", ":id: "+codigo, true);
                eb.addField(" ", " ", false);
                eb.addField("Acesse agora mesmo o computador de bordo!", ":speech_balloon: Baixe direto pelo link: "+config.linkB, false);
                */
                //eb.setFooter("Computador de Bordo [ver. "+config.versao+"]", null);
                Instant instant = Instant.from(ZonedDateTime.now());
                eb.setTimestamp(instant);
                eb.setThumbnail(url_logo);

                usuar.openPrivateChannel().queue((channel) ->
                {
                    channel.sendMessage(eb.build()).queue();
                });
            }else{
                showMessageDialog(null,
                    "Não conseguimos localizar o Discord de "+nome+".",
                    "Discord não encontrado!",
                    JOptionPane.ERROR_MESSAGE);
            }
    }
    
    public void MensagemHierarquia(JSONObject dados){
        
        //MUDAR ESSAS COISAS
        //String Titulo = dados.getString("oqfez");
        Usuario usuario = new Usuario();
        JSONObject obj = Usuario.UsuarioMain;//new JSONObject(usuario.getDados());
        
        String id_usuario = dados.getString("passaporte");
        String id_promoveu = obj.getString("id_usuario");
        
        String nome_usuario = dados.getString("nome");
        String nome_promoveu = obj.getString("nome")+" "+obj.getString("sobrenome");
        String patente = dados.getString("nome_patente");
        
        String Texto = "**"+nome_usuario+"** foi **recrutado** para a "+config.Abv_NomePolicia+" como **"+patente+"**.";
        
        int cor = 0x339933;
        
        String canal="669698732517752852";
        TextChannel usuar = jda.getTextChannelById​(Long.parseLong(canal));
        if(usuar != null){
            EmbedBuilder eb = new EmbedBuilder();
            eb.setTitle("Adição na hierarquia", null);
            eb.setColor(new Color(cor));
            eb.setDescription(Texto);
            eb.addField("Policial recrutado", nome_usuario+" ("+id_usuario+")", true);
            eb.addField("Oficial recrutador", nome_promoveu+" ("+id_promoveu+")", true);
            eb.addField("Patente", patente, true);

            eb.setFooter("Computador de Bordo [ver. "+config.versao+"]", null);

            eb.setThumbnail(config.img_DiscordPolicia);
            Instant instant = Instant.from(ZonedDateTime.now());
            eb.setTimestamp(instant);

            usuar.sendMessage(eb.build()).queue();
        }
    }
    
    
    
    public void AtualizarInfo(){
        //System.out.print(membros.getValueAt(membros.getSelectedRow(), 2).toString());
        String PassSelecionado = "0";
        newcodigo=false;
        if(membros.getSelectedRow() < 0){
            if(nomeusuariog.length() > 0)PassSelecionado = nomeusuariog;
        }else{
            PassSelecionado = membros.getValueAt(membros.getSelectedRow(), 0).toString();
            nomeusuariog = PassSelecionado;
        }
        for(int i = 0; i < InicializadorMain.usuariosDBarray.length(); i++){
            JSONObject o = InicializadorMain.usuariosDBarray.getJSONObject(i);
            int paser = Integer.parseInt(PassSelecionado);
            if(paser==o.getInt("id_usuario")){
                int pass = o.getInt("id_usuario");
                String discord = Usuario.DiscordPorID(pass);
                String nome = o.getString("nome");
                String sobrenome = o.getString("sobrenome");
                String codigo = o.getString("codigo");
                //System.out.println("usuariosDBarray: "+o.toString()+" ?°/ ");

                int pter=0;
                int pter2=0;
                int pins=0;
                boolean checker=false;
                long dater=0;
                long datar=0;
                /*
                for(int i2 = 0; i2 < hierarquiaDBarray.length(); i2++){
                    JSONObject ohier = hierarquiaDBarray.getJSONObject(i2);
                    //System.out.println("hierarquiaDBarray: "+ohier.toString()+" // ");
                    if(pass==ohier.getInt("id_usuario")){
                        pter = ohier.getInt("cargo");
                        pter2= ohier.getInt("cargo_antigo");
                        datar= ohier.getLong("data");
                        pins=ohier.getInt("stars");
                        if(!checker){
                            checker=true;
                            dater=ohier.getLong("data");
                        }
                    }
                }*/
                //JSONObject Hie_userid = SNWindows.getLastHierarquiaPorID(pass);
                JSONObject cargo_usuario = SNWindows.getCargoObjUserID(pass);
                String patente = cargo_usuario.getString("nome_cargo");//usuarios.Patentes(pter);
                String patenteo = cargo_usuario.getString("nome_cargo");//usuarios.Patentes(pter2);
                PatenteP=cargo_usuario.getInt("id");
                PatentePA=PatenteP;
                PatenteInsigna=pins;
                PatenteInsignaA=pins;
                
                PrettyTime p = new PrettyTime();
                long ultimologin = o.getLong("ultimologin");
                String ErOq;
                if(ultimologin < 10000){
                    ErOq= "Nunca";
                }else{
                    ErOq= p.format(new Date(ultimologin));
                }
                
                vl_acesso.setText(ErOq);

                //usuarios.Patentes();

                //cid.setText(pass+"");
                nome_usuario.setText(nome+" "+sobrenome+" ("+pass+")");
                //cnome1.setText(sobrenome);
                
                //ccodigo.setText(codigo);
                //ccodigo.setText("•••••");
                //cdiscord.setText(discord);

                //nome_usuario.setText(nome);
                
                /*
                String PttInsi2="";
                switch (PatenteInsigna) {
                    case 0:
                        PttInsi2= " [■■■]";
                        break;
                    case 1:
                        PttInsi2= " [*■■]";
                        break;
                    case 2:
                        PttInsi2= " [**■]";
                        break;
                    case 3:
                        PttInsi2= " [***️]";
                        break;
                    default:
                        PttInsi2= " [■■■]";
                        break;
                }
                pttatual.setText(patente+" "+PttInsi2);
                */
                pttatual.setText(patente);
                newptt.setText(patente);

                vl_lastptt.setText(patenteo);

                NomeP=nome+" "+sobrenome;
                //PatenteP=resulteSet.getInt("patente");
                PatentePA=PatenteP;
                CodigoP=codigo;
                Discord=discord;
                PassaporteP=pass;

                /*
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);
                btexonerado.setEnabled(true);*/
                bt_rebaixar.setEnabled(false);
                bt_promover.setEnabled(false);
                btexonerado.setEnabled(true);

                //editar.setEnabled(true);


                //System.out.println(p.format(new Date(System.currentTimeMillis() - 1000*60*10)));
                //System.out.println(System.currentTimeMillis());
                
                // VERIFICAR PRISOES DO POLICIAL
                int prisoesp = 0;
                int multarp = 0;
                for(int i2 = 0; i2 < InicializadorMain.prisoesDBarray.length(); i2++){
                    JSONObject o2 = InicializadorMain.prisoesDBarray.getJSONObject(i2);
                    if(pass == o2.getInt("id_prendeu") && o2.getInt("pagou") > 0){
                        if(o2.getInt("meses") > 0){
                            prisoesp++;
                        }else if(o2.getInt("multas") > 0){
                            multarp++;
                        }
                    }
                }
                String TextoPre1 = "Nenhuma";
                if(prisoesp == 1){
                    TextoPre1 = "Uma Prisão";
                }else if(prisoesp > 1){
                    TextoPre1 = prisoesp+" Prisões";
                }
                
                String TextoPre2 = "Nenhuma";
                if(multarp == 1){
                    TextoPre2 = "Uma Multa";
                }else if(multarp > 1){
                    TextoPre2 = multarp+" Multas";
                }
                    
                vl_prisoes.setText(TextoPre1);
                vl_multas.setText(TextoPre2);
                
                if(datar < 10000){
                    ErOq= "Nunca";
                }else{
                    ErOq= p.format(new Date(datar));
                }
                vl_lastpromocao.setText(ErOq);

                if(dater < 10000){
                    ErOq= "Nunca";
                }else{
                    ErOq= p.format(new Date(dater));
                }
                vl_entrou.setText(ErOq);
            }
        }
        
        AtualizarPtt();
        DesativarCampos();
        
        /*
        //System.out.print(membros.getSelectedRow(), 2));
        ResultSet resulteSet = null;
        resulteSet = conexao.readDataBase2("usuarios", "passaporte", PassSelecionado);
        
        long datar=System.currentTimeMillis();
        try {
            while (resulteSet.next()) {
                PrettyTime p = new PrettyTime();
                String nome = resulteSet.getString("nome");
                //String patente = usuarios.Patentes(resulteSet.getInt("patente"));
                
                String pass = resulteSet.getString("passaporte");
                String discord = resulteSet.getString("discord");
                String codigo = resulteSet.getString("codigo");
                
                long ultimologin = resulteSet.getLong("ultimologin");
                jLabel22.setText(p.format(new Date(ultimologin)));
                
                //usuarios.Patentes();
                
                ResultSet resulta = conexao.getUltimaPatente("hierarquia", "id_usuario", pass, "DESC");
                int pater=0;
                
                while(resulta.next()) {
                    PatenteP = Integer.parseInt(resulta.getString("cargo"));
                    pater = Integer.parseInt(resulta.getString("cargo_antigo"));
                    datar=resulta.getLong("data");
                    
                }
                String patente = usuarios.Patentes(PatenteP);
                String patenteo = usuarios.Patentes(pater);
                cid.setText(pass);
                cnome.setText(nome);
                ccodigo.setText(codigo);
                cdiscord.setText(discord);
                
                nomeptt.setText(nome);
                
                pttatual.setText(patente);
                newptt.setText(patente);
                
                jLabel36.setText(patenteo);
                
                NomeP=nome;
                //PatenteP=resulteSet.getInt("patente");
                PatentePA=PatenteP;
                CodigoP=codigo;
                PassaporteP=Integer.parseInt(pass);
                
                jButton3.setEnabled(true);
                jButton4.setEnabled(true);
                
                btexonerado.setEnabled(true);
                
                editar.setEnabled(true);
                
                
                //System.out.println(p.format(new Date(System.currentTimeMillis() - 1000*60*10)));
                System.out.println(System.currentTimeMillis());
                jLabel35.setText(p.format(new Date(datar)));
                
                ResultSet resulta2 = conexao.getUltimaPatente("hierarquia", "id_usuario", pass, "ASC");
                long dater=System.currentTimeMillis();
                while(resulta2.next()){
                    dater=resulta2.getLong("data");
                }
                jLabel44.setText(p.format(new Date(dater)));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Corporacao.class.getName()).log(Level.SEVERE, null, ex);
        }
        */
    }
    
    
    public void AtualizarPtt(){ //ATIVAR DPS DE ARRUMAR
        int QuantidadePtts = SNWindows.getCargos().length();
        if(PatenteP == QuantidadePtts){
            bt_rebaixar.setEnabled(false);
        }else{
            bt_rebaixar.setEnabled(true);
        }
        if(PatenteP == 1 && PatenteInsigna == 0){
            bt_promover.setEnabled(false);
        }else{
            bt_promover.setEnabled(true);
        }
        if(PatenteP == 99){
            bt_promover.setEnabled(false);
            bt_rebaixar.setEnabled(true);
            PatenteInsigna=0;
        }
        
        if(PatenteP < 1){
            PatenteP = 1;
        }else
        if(PatenteP == 99){
            PatenteP=99;
        }else
        if(PatenteP > QuantidadePtts){
            PatenteP=QuantidadePtts;
        }
        btexonerado.setEnabled(true);
        
        /*
        String PttInsi="";
        switch (PatenteInsigna) {
            case 0:
                PttInsi= " [■■■]";
                break;
            case 1:
                PttInsi= " [*■■]";
                break;
            case 2:
                PttInsi= " [**■]";
                break;
            case 3:
                PttInsi= " [***️]";
                break;
            default:
                PttInsi= " [■■■]";
                break;
        }*/
        String frmtPtt=SNWindows.getCargoPorID(PatenteP).getString("nome_cargo");//usuarios.Patentes(PatenteP);
        /*if(PatenteP < 12){
            frmtPtt+=PttInsi;
        }*/
        newptt.setText(frmtPtt);
        
        int condif = PatenteP-PatentePA;
        String Dife = "";
        if(condif != 0){
            if(condif > 0){
                Dife="  ▼"+condif;
            }else{
                Dife="  ▲"+(condif*-1);
            }
        }
        
        tt_newptt.setText("NOVA PATENTE"+Dife);
        Alterou();
    }
    
    
    public void SalvarDados(){
        /*
        String pass = cid.getText();
        //boolean passou = conexao.getPossuiRegistro("cb_identities", "id", pass);
        //if(!passou){
            
            JSONObject my_obj = new JSONObject();
            String nome = cnome.getText();
            String sobrenome = cnome1.getText();
            //String discord = cdiscord.getText();
            String codigo = ccodigo.getText();
            my_obj.put("passaporte", pass);
            //my_obj.put("nome", nome+" "+sobrenome);
            my_obj.put("codigo", codigo);
            //my_obj.put("discord", Usuario.DiscordPorID(Integer.parseInt(pass)));
            //my_obj.put("nome_patente", "");
            //my_obj.put("oqfez", 0);
            if(conexao.AtualizarDatabaseDado("cb_users", my_obj)){
                int dialogButton = JOptionPane.YES_NO_OPTION;
                if(newcodigo){
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Deseja enviar o novo código para "+nome+" "+sobrenome+" ?", "Envio de código no discord", dialogButton);
                    if(dialogResult == 0) {
                        MensagemDiscord(my_obj);
                        //System.out.print("Mensagem enviada para: "+discord+" /// ");
                    } else {
                        System.out.println("Opção de não.");
                    } 
                }
                //AttDBUsuarios();
                policia.AttDBSTodas();
                usuariosDBarray = InicializadorMain.usuariosDBarray;
                discordDBarray = InicializadorMain.discordDBarray;
                //usuariosDBarray = policia.AttDBUsuarios();
                AttDBHierarquia();
                TabelaAtt();
                AtualizarInfo();
                
            }
            */
        /*
            }else{
            showMessageDialog(null,
            "Já existe um usuário com o passaporte "+pass+"!",
            "Desculpe, tente outro passaporte",
            JOptionPane.ERROR_MESSAGE);
        }*/
        newcodigo=false;
    }
    
    public void Erro(String Texto){
        if("".equals(Texto)){
            PainelErro.setVisible(false);
            ErroTxt.setText(" ");
        }else{
            PainelErro.setVisible(true);
            ErroTxt.setText(Texto.toUpperCase());
        }
        pack();
    }
    
    public void AdicionarUser(){
        String tpassa = txtPassaporte.getText();
        
        if(tpassa.length() <= 0 && Integer.parseInt(tpassa) <= 0){
            Erro("Digite um passaporte válido");
            return;
        }
        int passause = Integer.parseInt(tpassa);
        JSONObject usuario_recrutar = ConfigUsuario.getUsuarioPorID(passause);
        if(usuario_recrutar == null){
            Erro("Usuário não encontrado");
            return ;
        }   
        
        long datar=System.currentTimeMillis();
        boolean conte=false;
        boolean lspde=false;
        String nomw=usuario_recrutar.getString("nome");
        String sobw=usuario_recrutar.getString("sobrenome");

        if("".equals(nomw)) nomw="Sujeito";
        if("".equals(sobw)) nomw="Indigente";
        
        ErroTxt.setText(nomw+" "+sobw+" ("+passause+")");
        NomeU=nomw+" "+sobw;
            
            
        JSONObject obj = Usuario.UsuarioMain;//new JSONObject(usuario.getDados());
        
        if(ConfigUsuario.EhPolicial(passause)){
            //JOptionPane.showMessageDialog(null, NomeU+" ("+PassaAddU+") já está na Polícia como "+usuarios.Patentes(pter)+".", "Já está na "+config.Abv_NomePolicia, JOptionPane.PLAIN_MESSAGE);
            Erro(NomeU+" ("+PassaAddU+") já é um policial");
        }else{
            
            // REFAZER TODO O CÓDIGO DE SALVAMENTO DE RECRUTAMENTO
            JSONObject AddLSPD = new JSONObject();
            AddLSPD.put("passaporte", PassaAddU);
            AddLSPD.put("nome", NomeU);
            //AddLSPD.put("discord", DiscordAddU);
            String Codegor = randomAlphaNumeric(4);
            AddLSPD.put("codigo", Codegor);
            nomeusuariog=PassaAddU;

            //AddLSPD.put("patente", Bpatentes.getSelectedIndex()+"");
            AddLSPD.put("passaporteP", obj.getString("id_usuario"));
            AddLSPD.put("nomeP", obj.getString("nome"));
            //AddLSPD.put("nome_patente", usuarios.Patentes(Bpatentes.getSelectedIndex()));
            String Discordae="";
            int temconta=0;
            for(int i = 0; i < InicializadorMain.usuariosDBarray.length(); i++){
                JSONObject user = InicializadorMain.usuariosDBarray.getJSONObject(i);
                int pass = user.getInt("id_usuario");
                /*
                if(pass == passause){
                    if(!"".equals(user.getString("discord"))){
                        //Discordae=user.getString("discord");
                        temconta=1;
                    }
                }*/
            }
            for(int idis = 0; idis < discordDBarray.length(); idis++){
                JSONObject disc = discordDBarray.getJSONObject(idis);
                int use_id = disc.getInt("user_id");
                if(use_id == passause)Discordae = disc.getString("identifier");
            }
            AddLSPD.put("discord", Discordae);
            AddLSPD.put("newuser", temconta);
            AddLSPD.put("oqfez", 1);
            if(conexao.AddUserLSPD(AddLSPD)){
                System.out.print("deu certo!!");
                //MensagemDiscord("kli0ns#3092","Seu código foi alterado!!","Seu novo código é: ASDA");
                
                JOptionPane.showMessageDialog(null, "O código de "+NomeU+" ("+PassaAddU+") é: "+Codegor, "Código gerado para o Usuário", JOptionPane.PLAIN_MESSAGE);
            }
            if(!"".equals(Discordae)){
                int dialogButton = JOptionPane.YES_NO_OPTION;
                int dialogResult = JOptionPane.showConfirmDialog(this, "Deseja enviar o novo código para "+NomeU+" ?", "Envio de código no discord", dialogButton);
                if(dialogResult == 0) {
                    //MensagemDiscord(AddLSPD);
                    System.out.print("Mensagem enviada para: "+Discordae+" /// ");
                } else {
                    System.out.println("Opção de não.");
                } 
            }
            //AttDBHierarquia();
            //MensagemHierarquia(AddLSPD);
        }
        
        AttDBUsuarios();
        InicializadorMain.AttDBSHierarquia();
        AttDBHierarquia();
        TabelaAtt();
        AtualizarInfo();
    }
    
    public void AttDBUsuarios(){
        //policia.AttDBUsuariosSet();
        usuariosDBarray = InicializadorMain.usuariosDBarray;//policia.AttDBUsuarios();
    }
    
    public void AttDBHierarquia(){
        hierarquiaDBarray = InicializadorMain.hierarquiaDBarray;//usuarios.AttDBHierarquia();
    }
    
    
    public void AtivarCampos(){
        //cid.setEnabled(true);
        //cnome.setEnabled(true);
        //cnome1.setEnabled(true);
        //ccodigo.setEnabled(true);
        //cdiscord.setEnabled(true);
        //editar.setVisible(false);
        //salvar.setEnabled(true);
        //desfazer.setVisible(true);
        //btCodigo.setEnabled(true);
        pack();
    }
    
    public void DesativarCampos(){
        //cid.setEnabled(false);
        //cnome.setEnabled(false);
        //cnome1.setEnabled(false);
        //ccodigo.setEnabled(false);
        //cdiscord.setEnabled(false);
        //editar.setVisible(true);
        //salvar.setEnabled(false);
        //desfazer.setVisible(false);
        //btCodigo.setEnabled(false);
        pack();
    }
    
    public boolean SomenteNumeros(KeyEvent evt){
        char c = evt.getKeyChar();
        if (!((c >= '0') && (c <= '9') ||
            (c == KeyEvent.VK_BACK_SPACE) ||
            (c == KeyEvent.VK_DELETE) ||
            (c == KeyEvent.VK_LEFT) ||
            (c == KeyEvent.VK_RIGHT)) ) {
            //getToolkit().beep();
            evt.consume();
        }
        return true;
    }
    
    public static String randomAlphaNumeric(int count) {
        StringBuilder builder = new StringBuilder();
        while (count-- != 0) {
            int character = (int)(Math.random()*ALPHA_NUMERIC_STRING.length());
            builder.append(ALPHA_NUMERIC_STRING.charAt(character));
        }
        return builder.toString();
    }
    
    public void Selecionar(){
        String PassSelecionado = membros.getValueAt(membros.getSelectedRow(), 0).toString();
        //if(!PassSelecionado.equals(cid.getText())){
            //System.out.print("Já foi selecionado");
            //System.out.print("Não foi selecionado");
            AtualizarInfo();
        //}
    }
    
    public void PesquisarT(){
        DefaultTableModel table = (DefaultTableModel)membros.getModel();
        String search = pesquisa.getText().toLowerCase();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
        membros.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter("(?i)" +search));
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo_pagina = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSeparator4 = new javax.swing.JSeparator();
        informacoes = new javax.swing.JPanel();
        tt_infodetal = new javax.swing.JLabel();
        tt_acesso = new javax.swing.JLabel();
        vl_acesso = new javax.swing.JLabel();
        tt_prisoes = new javax.swing.JLabel();
        vl_prisoes = new javax.swing.JLabel();
        tt_multas = new javax.swing.JLabel();
        vl_multas = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        titulo_cursos = new javax.swing.JLabel();
        vl_cursos = new javax.swing.JLabel();
        bt_cursos = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        titulo_hierarquia = new javax.swing.JLabel();
        tt_lastpromocao = new javax.swing.JLabel();
        vl_lastpromocao = new javax.swing.JLabel();
        tt_lastptt = new javax.swing.JLabel();
        vl_lastptt = new javax.swing.JLabel();
        tt_entrou = new javax.swing.JLabel();
        vl_entrou = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        config_usuario = new javax.swing.JPanel();
        nome_usuario = new javax.swing.JLabel();
        tt_ptt = new javax.swing.JLabel();
        pttatual = new javax.swing.JLabel();
        tt_newptt = new javax.swing.JLabel();
        newptt = new javax.swing.JLabel();
        bt_promover = new javax.swing.JButton();
        bt_rebaixar = new javax.swing.JButton();
        btexonerado = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JSeparator();
        desfazer_alteracoes = new javax.swing.JButton();
        salvar_ptt = new javax.swing.JButton();
        btexonerado1 = new javax.swing.JButton();
        btexonerado2 = new javax.swing.JButton();
        tt_advs = new javax.swing.JLabel();
        pnl_recrutar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtPassaporte = new javax.swing.JTextField();
        AddCorp = new javax.swing.JButton();
        PainelErro = new javax.swing.JPanel();
        ErroTxt = new javax.swing.JLabel();
        pnl_ativos = new javax.swing.JPanel();
        pesquisa = new javax.swing.JTextField();
        attTab = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        membros = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GERENCIAR CORPORAÇÃO");
        setResizable(false);

        titulo_pagina.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        titulo_pagina.setForeground(new java.awt.Color(255, 255, 255));
        titulo_pagina.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_pagina.setText("GERENCIAR CORPORAÇÃO");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "INFORMAÇÃO DO MEMBRO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);

        jPanel6.setOpaque(false);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);

        tt_infodetal.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        tt_infodetal.setForeground(new java.awt.Color(255, 255, 255));
        tt_infodetal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_infodetal.setText("INFORMAÇÕES DETALHADAS");

        tt_acesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_acesso.setForeground(new java.awt.Color(255, 255, 255));
        tt_acesso.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tt_acesso.setText("ÚLTIMO ACESSO:");

        vl_acesso.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_acesso.setForeground(new java.awt.Color(255, 255, 255));
        vl_acesso.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vl_acesso.setText("14/11/2019 ÁS 21:00");

        tt_prisoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_prisoes.setForeground(new java.awt.Color(255, 255, 255));
        tt_prisoes.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tt_prisoes.setText("PRISÕES REALIZADAS:");

        vl_prisoes.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_prisoes.setForeground(new java.awt.Color(255, 255, 255));
        vl_prisoes.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vl_prisoes.setText("[Em desenvolvimento]");

        tt_multas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_multas.setForeground(new java.awt.Color(255, 255, 255));
        tt_multas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tt_multas.setText("MULTAS DADAS:");

        vl_multas.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_multas.setForeground(new java.awt.Color(255, 255, 255));
        vl_multas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vl_multas.setText("[Em desenvolvimento]");

        titulo_cursos.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        titulo_cursos.setForeground(new java.awt.Color(255, 255, 255));
        titulo_cursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_cursos.setText("CURSOS E APRIMORAMENTOS");

        vl_cursos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_cursos.setForeground(new java.awt.Color(255, 255, 255));
        vl_cursos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        vl_cursos.setText("NÃO SELECIONADO");

        bt_cursos.setBackground(new java.awt.Color(255, 255, 255));
        bt_cursos.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        bt_cursos.setText("ADICIONAR/ REMOVER");

        titulo_hierarquia.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        titulo_hierarquia.setForeground(new java.awt.Color(255, 255, 255));
        titulo_hierarquia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo_hierarquia.setText("HIERARQUIA");

        tt_lastpromocao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_lastpromocao.setForeground(new java.awt.Color(255, 255, 255));
        tt_lastpromocao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tt_lastpromocao.setText("ÚLTIMA PROMOÇÃO:");

        vl_lastpromocao.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_lastpromocao.setForeground(new java.awt.Color(255, 255, 255));
        vl_lastpromocao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vl_lastpromocao.setText("Nada selecionado");

        tt_lastptt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_lastptt.setForeground(new java.awt.Color(255, 255, 255));
        tt_lastptt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tt_lastptt.setText("ÚLTIMA PATENTE:");

        vl_lastptt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_lastptt.setForeground(new java.awt.Color(255, 255, 255));
        vl_lastptt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vl_lastptt.setText("Nada selecionado");

        tt_entrou.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_entrou.setForeground(new java.awt.Color(255, 255, 255));
        tt_entrou.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        tt_entrou.setText("ENTROU NA CORPORAÇÃO:");

        vl_entrou.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        vl_entrou.setForeground(new java.awt.Color(255, 255, 255));
        vl_entrou.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        vl_entrou.setText("Nada selecionado");

        jLabel42.setForeground(new java.awt.Color(255, 255, 255));
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("[EM DESENVOLVIMENTO]");

        javax.swing.GroupLayout informacoesLayout = new javax.swing.GroupLayout(informacoes);
        informacoes.setLayout(informacoesLayout);
        informacoesLayout.setHorizontalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator5)
                    .addComponent(titulo_cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tt_infodetal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator7)
                    .addComponent(titulo_hierarquia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(informacoesLayout.createSequentialGroup()
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tt_entrou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tt_lastptt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tt_lastpromocao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(vl_lastptt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vl_lastpromocao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(vl_entrou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(informacoesLayout.createSequentialGroup()
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tt_multas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tt_prisoes, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(tt_acesso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vl_acesso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vl_prisoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(vl_multas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(vl_cursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacoesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bt_cursos)))
                .addContainerGap())
        );
        informacoesLayout.setVerticalGroup(
            informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tt_infodetal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_acesso, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt_prisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_prisoes, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt_multas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_multas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo_cursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vl_cursos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_cursos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titulo_hierarquia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt_lastpromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_lastpromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt_lastptt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_lastptt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(informacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tt_entrou, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vl_entrou, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addContainerGap())
        );

        nome_usuario.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        nome_usuario.setForeground(new java.awt.Color(255, 255, 255));
        nome_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nome_usuario.setText("NÃO SELECIONADO");

        tt_ptt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tt_ptt.setForeground(new java.awt.Color(255, 255, 255));
        tt_ptt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_ptt.setText("PATENTE ATUAL");

        pttatual.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        pttatual.setForeground(new java.awt.Color(255, 255, 255));
        pttatual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pttatual.setText("Não selecionado");

        tt_newptt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tt_newptt.setForeground(new java.awt.Color(255, 255, 255));
        tt_newptt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_newptt.setText("NOVA PATENTE");

        newptt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        newptt.setForeground(new java.awt.Color(255, 255, 255));
        newptt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        newptt.setText("Não selecionado");

        bt_promover.setBackground(new java.awt.Color(0, 153, 102));
        bt_promover.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bt_promover.setForeground(new java.awt.Color(255, 255, 255));
        bt_promover.setText("PROMOVER ▲");
        bt_promover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_promoverActionPerformed(evt);
            }
        });

        bt_rebaixar.setBackground(new java.awt.Color(255, 102, 51));
        bt_rebaixar.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        bt_rebaixar.setForeground(new java.awt.Color(255, 255, 255));
        bt_rebaixar.setText("▼ REBAIXAR");
        bt_rebaixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_rebaixarActionPerformed(evt);
            }
        });

        btexonerado.setBackground(new java.awt.Color(255, 255, 255));
        btexonerado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btexonerado.setText("EXONERAR");
        btexonerado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexoneradoActionPerformed(evt);
            }
        });

        desfazer_alteracoes.setBackground(new java.awt.Color(255, 255, 255));
        desfazer_alteracoes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desfazer_alteracoes.setText("DESFAZER ALTERAÇÕES");
        desfazer_alteracoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                desfazer_alteracoesActionPerformed(evt);
            }
        });

        salvar_ptt.setBackground(new java.awt.Color(255, 255, 255));
        salvar_ptt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        salvar_ptt.setText("SALVAR PATENTE");
        salvar_ptt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_pttActionPerformed(evt);
            }
        });

        btexonerado1.setBackground(new java.awt.Color(255, 255, 255));
        btexonerado1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btexonerado1.setText("+1");
        btexonerado1.setEnabled(false);
        btexonerado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexonerado1ActionPerformed(evt);
            }
        });

        btexonerado2.setBackground(new java.awt.Color(255, 255, 255));
        btexonerado2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        btexonerado2.setText("+2");
        btexonerado2.setEnabled(false);
        btexonerado2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btexonerado2ActionPerformed(evt);
            }
        });

        tt_advs.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tt_advs.setForeground(new java.awt.Color(255, 255, 255));
        tt_advs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tt_advs.setText("ADVERTÊNCIAS:");

        javax.swing.GroupLayout config_usuarioLayout = new javax.swing.GroupLayout(config_usuario);
        config_usuario.setLayout(config_usuarioLayout);
        config_usuarioLayout.setHorizontalGroup(
            config_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(config_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(config_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nome_usuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tt_ptt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btexonerado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pttatual, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(tt_newptt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(newptt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(desfazer_alteracoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator8)
                    .addComponent(salvar_ptt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(config_usuarioLayout.createSequentialGroup()
                        .addComponent(bt_promover, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_rebaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(config_usuarioLayout.createSequentialGroup()
                        .addComponent(tt_advs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btexonerado1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btexonerado2)))
                .addContainerGap())
        );
        config_usuarioLayout.setVerticalGroup(
            config_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(config_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nome_usuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tt_ptt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pttatual)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tt_newptt, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newptt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(config_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_promover, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_rebaixar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(config_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(config_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btexonerado1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btexonerado2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tt_advs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btexonerado, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(desfazer_alteracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvar_ptt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(config_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(informacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(config_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator4)
                    .addComponent(informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnl_recrutar.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "RECRUTAR", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSAPORTE:");

        txtPassaporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassaporteKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPassaporteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPassaporteKeyTyped(evt);
            }
        });

        AddCorp.setBackground(new java.awt.Color(255, 255, 255));
        AddCorp.setText("✔");
        AddCorp.setEnabled(false);
        AddCorp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCorpActionPerformed(evt);
            }
        });

        PainelErro.setBackground(new java.awt.Color(255, 51, 51));

        ErroTxt.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        ErroTxt.setForeground(new java.awt.Color(255, 255, 255));
        ErroTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ErroTxt.setText("AASDAWD");

        javax.swing.GroupLayout PainelErroLayout = new javax.swing.GroupLayout(PainelErro);
        PainelErro.setLayout(PainelErroLayout);
        PainelErroLayout.setHorizontalGroup(
            PainelErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ErroTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
        );
        PainelErroLayout.setVerticalGroup(
            PainelErroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelErroLayout.createSequentialGroup()
                .addComponent(ErroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_recrutarLayout = new javax.swing.GroupLayout(pnl_recrutar);
        pnl_recrutar.setLayout(pnl_recrutarLayout);
        pnl_recrutarLayout.setHorizontalGroup(
            pnl_recrutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_recrutarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_recrutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_recrutarLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPassaporte, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddCorp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PainelErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_recrutarLayout.setVerticalGroup(
            pnl_recrutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_recrutarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelErro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(pnl_recrutarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddCorp, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(txtPassaporte, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addContainerGap())
        );

        pnl_ativos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)), "MEMBROS ATIVOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        pnl_ativos.setOpaque(false);

        pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesquisaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesquisaKeyTyped(evt);
            }
        });

        attTab.setBackground(new java.awt.Color(255, 255, 255));
        attTab.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        attTab.setText("ATUALIZAR (ddd)");
        attTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attTabActionPerformed(evt);
            }
        });

        membros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PASSAPORTE", "NOME", "PATENTE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        membros.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        membros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                membrosMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                membrosMousePressed(evt);
            }
        });
        membros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                membrosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                membrosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(membros);

        javax.swing.GroupLayout pnl_ativosLayout = new javax.swing.GroupLayout(pnl_ativos);
        pnl_ativos.setLayout(pnl_ativosLayout);
        pnl_ativosLayout.setHorizontalGroup(
            pnl_ativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ativosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(pnl_ativosLayout.createSequentialGroup()
                        .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(attTab, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_ativosLayout.setVerticalGroup(
            pnl_ativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ativosLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnl_ativosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attTab, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu2.setText("FECHAR");

        jMenuItem2.setText("VOLTAR PARA O PAINEL");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("EXIBIR");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem3.setText("SOBRE");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo_pagina, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_recrutar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_ativos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 22, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo_pagina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_recrutar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl_ativos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddCorpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCorpActionPerformed
        AdicionarUser();
    }//GEN-LAST:event_AddCorpActionPerformed

    private void membrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membrosMouseClicked
        Selecionar();
    }//GEN-LAST:event_membrosMouseClicked

    private void bt_promoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_promoverActionPerformed
        /*if(PatenteP < 12){
            if(PatenteInsigna <= 0){
                PatenteP--;
                PatenteInsigna=3;
            }else{
                PatenteInsigna--;
            }
        }else if(PatenteP==12){
            PatenteP--;
            PatenteInsigna=3;
        }else{
            PatenteP--;
        }*/
        PatenteP--;
        AtualizarPtt();
    }//GEN-LAST:event_bt_promoverActionPerformed

    private void bt_rebaixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_rebaixarActionPerformed
        if(PatenteP == 99){
            PatenteP=0;
            PatenteInsigna=0;
        }else{
            PatenteP++;
            /*
            if(PatenteP < 12){
                if(PatenteInsigna >=3){
                    PatenteP++;
                    PatenteInsigna=0;
                }else{
                    PatenteInsigna++;
                }
            }else{
                PatenteP++;
            }*/
        }
        AtualizarPtt();
    }//GEN-LAST:event_bt_rebaixarActionPerformed

    private void btexoneradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexoneradoActionPerformed
        /*
        PatenteP=99;
        PatenteInsigna=0;
        newptt.setText("EXONERADO");
        btexonerado.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(true);
        
        Alterou();
        */
        JSONObject obj = Usuario.UsuarioMain;//new JSONObject(usuario.getDados());
        if(Integer.parseInt(obj.getString("id_usuario")) == PassaporteP){
            showMessageDialog(null,"Impossível excluir o seu próprio acesso.","Ocorreu um erro",JOptionPane.PLAIN_MESSAGE);
            System.err.println("ERRO AO EXCLUIR PROPRIO ACESSO");
        }else{
            Object[] options = { "Sim, excluir", "Não, cancelar" }; 
            int Escolha=JOptionPane.showOptionDialog(null,
                "Tem certeza que deseja excluir o acesso de "+NomeP+"?", // \n
                "Excluir Acesso de Usuário", 
                JOptionPane.DEFAULT_OPTION, 
                JOptionPane.WARNING_MESSAGE, 
                null, 
                options, 
                options[0]);
            if(Escolha==JOptionPane.YES_OPTION){
                conexao.DeleteUserLSPD(PassaporteP);
                showMessageDialog(null,"O acesso de "+NomeP+" foi excluido com sucesso!","Acesso excluido",JOptionPane.PLAIN_MESSAGE);
                System.err.println("EXCLUIDO COM SUCESSO");
                InicializadorMain.AttDBSHierarquia();
                AttDBHierarquia();
                TabelaAtt();
            }
        }
    }//GEN-LAST:event_btexoneradoActionPerformed

    private void desfazer_alteracoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_desfazer_alteracoesActionPerformed
        AtualizarInfo();
        TabelaAtt();
        DesativarCampos();
        Alterou();
    }//GEN-LAST:event_desfazer_alteracoesActionPerformed

    private void salvar_pttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_pttActionPerformed
        
        JSONObject set_info = new JSONObject();
        Usuario usuario = new Usuario();
        JSONObject obj = Usuario.UsuarioMain;//new JSONObject(usuario.getDados());
        set_info=obj;
        /*set_info.put("nome", obj.getString("nome"));
        set_info.put("codigo", obj.getString("codigo"));
        set_info.put("discord", obj.getString("discord"));
        set_info.put("age", obj.getInt("age"));
        set_info.put("permissao", obj.getInt("permissao"));*/
        
        set_info.put("ptt_passaporte", PassaporteP+"");
        set_info.put("ptt_nome", NomeP);
        set_info.put("ptt_patente", PatenteP+"");
        set_info.put("ptt_patente_old", PatentePA+"");
        
        set_info.put("ptt_codigo", CodigoP);
        set_info.put("ptt_discord", Discord);
        set_info.put("ptt_stars", PatenteInsigna+"");
        set_info.put("ptt_stars_old", PatenteInsignaA+"");
        
        //salvar dados do usuário atual
        System.err.println("set_info: "+ set_info.toString()+"/ fechou");
        usuario.setDadosalvar(set_info);
        /*
        SalvarDadosCorporacao salvard = new SalvarDadosCorporacao();
        salvard.setVisible(true);
        this.dispose();
        */
    }//GEN-LAST:event_salvar_pttActionPerformed

    private void btexonerado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexonerado1ActionPerformed
        AddUser usuarios = new AddUser();
        //usuarios.AA="OLOKINHO";
        usuarios.setVisible(true);
    }//GEN-LAST:event_btexonerado1ActionPerformed

    private void btexonerado2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btexonerado2ActionPerformed
        //MensagemDiscord("kli0ns#3092","Seu código foi alterado!!","Seu novo código é: ASDA");
    }//GEN-LAST:event_btexonerado2ActionPerformed

    private void txtPassaporteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassaporteKeyPressed
        //SomenteNumeros(evt);
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            AdicionarUser();
        }
    }//GEN-LAST:event_txtPassaporteKeyPressed

    private void txtPassaporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassaporteKeyReleased
        SomenteNumeros(evt);
    }//GEN-LAST:event_txtPassaporteKeyReleased

    private void txtPassaporteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassaporteKeyTyped
        SomenteNumeros(evt);
    }//GEN-LAST:event_txtPassaporteKeyTyped

    private void membrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_membrosKeyReleased
        Selecionar();       // TODO add your handling code here:
    }//GEN-LAST:event_membrosKeyReleased

    private void membrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_membrosKeyTyped
        Selecionar();        // TODO add your handling code here:
    }//GEN-LAST:event_membrosKeyTyped

    private void membrosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_membrosMousePressed
        Selecionar();// TODO add your handling code here:
    }//GEN-LAST:event_membrosMousePressed

    private void attTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attTabActionPerformed
        //AttDBUsuarios();
        AttDBHierarquia();
        TabelaAtt();
    }//GEN-LAST:event_attTabActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new Painel().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        InicializadorMain.sobre.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void pesquisaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyTyped
        /*String text = pesquisa.getText();
        if (text.trim().length() == 0) {
           //rowSorter.setRowFilter(null);
        } else {
           membros.setRowFilter(RowFilter.regexFilter("(?i)" + text));
        }*/
        PesquisarT();
    }//GEN-LAST:event_pesquisaKeyTyped

    private void pesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaKeyReleased
        PesquisarT();
    }//GEN-LAST:event_pesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CorporacaoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CorporacaoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CorporacaoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CorporacaoUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CorporacaoUsuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddCorp;
    private javax.swing.JLabel ErroTxt;
    private javax.swing.JPanel PainelErro;
    private javax.swing.JButton attTab;
    private javax.swing.JButton bt_cursos;
    private javax.swing.JButton bt_promover;
    private javax.swing.JButton bt_rebaixar;
    private javax.swing.JButton btexonerado;
    private javax.swing.JButton btexonerado1;
    private javax.swing.JButton btexonerado2;
    private javax.swing.JPanel config_usuario;
    private javax.swing.JButton desfazer_alteracoes;
    private javax.swing.JPanel informacoes;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable membros;
    private javax.swing.JLabel newptt;
    private javax.swing.JLabel nome_usuario;
    private javax.swing.JTextField pesquisa;
    private javax.swing.JPanel pnl_ativos;
    private javax.swing.JPanel pnl_recrutar;
    private javax.swing.JLabel pttatual;
    private javax.swing.JButton salvar_ptt;
    private javax.swing.JLabel titulo_cursos;
    private javax.swing.JLabel titulo_hierarquia;
    private javax.swing.JLabel titulo_pagina;
    private javax.swing.JLabel tt_acesso;
    private javax.swing.JLabel tt_advs;
    private javax.swing.JLabel tt_entrou;
    private javax.swing.JLabel tt_infodetal;
    private javax.swing.JLabel tt_lastpromocao;
    private javax.swing.JLabel tt_lastptt;
    private javax.swing.JLabel tt_multas;
    private javax.swing.JLabel tt_newptt;
    private javax.swing.JLabel tt_prisoes;
    private javax.swing.JLabel tt_ptt;
    private javax.swing.JTextField txtPassaporte;
    private javax.swing.JLabel vl_acesso;
    private javax.swing.JLabel vl_cursos;
    private javax.swing.JLabel vl_entrou;
    private javax.swing.JLabel vl_lastpromocao;
    private javax.swing.JLabel vl_lastptt;
    private javax.swing.JLabel vl_multas;
    private javax.swing.JLabel vl_prisoes;
    // End of variables declaration//GEN-END:variables
}
