/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package police;

import police.configs.Usuario;
import java.awt.Toolkit;
import org.json.JSONObject;
import police.configs.Config;

/**
 *
 * @author John
 */
public class Painel extends javax.swing.JFrame {

    /**
     * Creates new form Painel
     */
    Usuario usuario = new Usuario();
    Config config = new Config();
    public Painel() {
        initComponents();
        this.setLocationRelativeTo(null);
        getContentPane().setBackground(new java.awt.Color(13, 32, 64));
        
        pessoas.setBackground(new java.awt.Color(13, 32, 64));
        pessoas1.setBackground(new java.awt.Color(13, 32, 64));
        //veiculos.setBackground(new java.awt.Color(50, 31, 87));
        
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource(config.img_CBIcone)));
        
        Carregar();
    }
    public void Carregar(){
        
        //System.err.println("getDados: "+ usuario.getDados()+"/ fechou");
        
        pessoas1.setVisible(false);
        
        JSONObject obj = new JSONObject(usuario.getDados());
        String nomer = obj.getString("sobrenome");
        //System.err.println("Already running."+ obj);
        logadocomo.setText("LOGADO COMO: "+nomer.toUpperCase());
        jLabel3.setText("BEM VINDO "+nomer.toUpperCase()+",");
        
        if(obj.getInt("permissao") >= 1) pessoas1.setVisible(true);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pessoas = new javax.swing.JPanel();
        crimes = new javax.swing.JButton();
        boletim = new javax.swing.JButton();
        logadocomo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pessoas1 = new javax.swing.JPanel();
        crimes1 = new javax.swing.JButton();
        crimes2 = new javax.swing.JButton();
        logadocomo1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPUTADOR DE BORDO");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("AO COMPUTADOR DE BORDO");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pessoas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "APLICATIVO ÚTIL", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        crimes.setBackground(new java.awt.Color(153, 153, 255));
        crimes.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        crimes.setText("REGISTROS");
        crimes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimesActionPerformed(evt);
            }
        });

        boletim.setBackground(new java.awt.Color(102, 102, 255));
        boletim.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        boletim.setText("BOLETIM");
        boletim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boletimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pessoasLayout = new javax.swing.GroupLayout(pessoas);
        pessoas.setLayout(pessoasLayout);
        pessoasLayout.setHorizontalGroup(
            pessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crimes, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(boletim, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pessoasLayout.setVerticalGroup(
            pessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pessoasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crimes, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boletim, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        logadocomo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logadocomo.setForeground(new java.awt.Color(255, 255, 255));
        logadocomo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        logadocomo.setText("LOGADO COMO NOMEJOGADOR");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("BEM VINDO NOME,");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/police/imagens/RC.png"))); // NOI18N

        pessoas1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "COMANDO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        crimes1.setBackground(new java.awt.Color(204, 204, 0));
        crimes1.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        crimes1.setText("GERENCIAR CORPORAÇÃO");
        crimes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimes1ActionPerformed(evt);
            }
        });

        crimes2.setBackground(new java.awt.Color(102, 204, 0));
        crimes2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        crimes2.setText("LIMPAR FICHA");
        crimes2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crimes2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pessoas1Layout = new javax.swing.GroupLayout(pessoas1);
        pessoas1.setLayout(pessoas1Layout);
        pessoas1Layout.setHorizontalGroup(
            pessoas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoas1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(crimes1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(crimes2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pessoas1Layout.setVerticalGroup(
            pessoas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pessoas1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pessoas1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crimes1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(crimes2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        logadocomo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logadocomo1.setForeground(new java.awt.Color(255, 255, 255));
        logadocomo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logadocomo1.setText("DESENVOLVIDO POR: kli0ns#3092");

        jMenu3.setText("EXIBIR");
        jMenu3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jMenuItem3.setText("SOBRE");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pessoas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pessoas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(logadocomo1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(logadocomo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addComponent(pessoas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pessoas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logadocomo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logadocomo1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimesActionPerformed
        new Prender().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crimesActionPerformed

    private void boletimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boletimActionPerformed
        new Boletim().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_boletimActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        InicializadorMain.sobre.setVisible(true);
        //this.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void crimes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimes1ActionPerformed
        new Corporacao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crimes1ActionPerformed

    private void crimes2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crimes2ActionPerformed
        new LimpezaFicha().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_crimes2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Painel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Painel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boletim;
    private javax.swing.JButton crimes;
    private javax.swing.JButton crimes1;
    private javax.swing.JButton crimes2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JLabel logadocomo;
    private javax.swing.JLabel logadocomo1;
    private javax.swing.JPanel pessoas;
    private javax.swing.JPanel pessoas1;
    // End of variables declaration//GEN-END:variables
}
