/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package police;

import java.awt.Toolkit;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import police.configs.Config;

/**
 *
 * @author John
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form VerCrimes
     */
    public int ValorProgresso=0;
    public int ProgressoAtual=0;
    public int ContandoFalhas=0;
    public boolean Fechar=false;
    public boolean Valendo=false;
    public int ContandoMargem=0;
    public SplashScreen() {
        initComponents();
        this.setLocationRelativeTo(null);
        //this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("imagens/mclost_1.png")));
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("imagens/lspd-small.png")));
        getContentPane().setBackground(new java.awt.Color(13, 32, 64));
        //patt.setBackground(new java.awt.Color(30, 11, 67));
        IniciarSobre();
        
    }
    public boolean IniciarSobre(){
        Config config;
        config = new Config();
        String versao = config.versao;
        int build = config.build;
        
        int ano = build / 10000;
        int mes = (build / 100)%100;
        int dia = build % 100;
        String De=dia+"";
        String Me=mes+"";
        String An=ano+"";
        if(dia<10)De="0"+De; if(mes<10)Me="0"+Me; if(ano<10)An="0"+An;
        String Att = De+"/"+Me+"/"+An;
        atualizadot.setText("(ATUALIZADO EM: "+Att+")");
        Timere();
        
        //if(config.VerificarAtt()) txtAtt.setText("ATUALIZAÇÃO DISPONÍVEL PARA: "+config.getVersao());
        return true;
    }
    public void Timere (){
        int delay = 500;   // tempo de espera antes da 1ª execução da tarefa.
        int interval = 500;  // intervalo no qual a tarefa será executada.
        Timer timer = new Timer();
        Random gerador = new Random();
        timer.scheduleAtFixedRate(new TimerTask() {
          public void run() {
            //System.out.print("CONTANDO: "+ValorProgresso+ " /////////// ");
            
            if(ValorProgresso>0){
                if(ValorProgresso > ProgressoAtual){
                    ProgressoAtual+=2+gerador.nextInt(10);
                }else{
                    ContandoFalhas++;
                    //System.out.print("ContandoFalhas: "+ContandoFalhas);
                }
            }else{
                ContandoMargem++;
            }
            if(ProgressoAtual>=100){
                ProgressoAtual=100;
                ContandoFalhas=0;
                timer.cancel();
                //progresso.setIndeterminate(true);
            }
            progresso.setValue(ProgressoAtual);
            if(ContandoFalhas > 36){
                texto.setText("CONEXÃO EXTREMAMENTE LENTA");
                if(ContandoFalhas > 60) texto.setText("FINALIZANDO PROGRAMA POR FALTA DE CONEXÃO");
                if(ContandoFalhas > 70) System.exit(0);
            }
            if(Fechar || ContandoMargem > 10)timer.cancel();
          }
        }, delay, interval);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        atualizadot = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COMPUTADOR DE BORDO");
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("COMPUTADOR DE BORDO");

        atualizadot.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        atualizadot.setForeground(new java.awt.Color(255, 255, 255));
        atualizadot.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        atualizadot.setText("(ATUALIZADO EM 25/10/19)");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/police/imagens/RC.png"))); // NOI18N

        texto.setForeground(new java.awt.Color(255, 255, 255));
        texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        texto.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(progresso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(atualizadot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                    .addComponent(texto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(titulo)
                        .addGap(18, 18, 18)
                        .addComponent(atualizadot)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(progresso, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(texto)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SplashScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel atualizadot;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JProgressBar progresso;
    public javax.swing.JLabel texto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
